// Generated by scripts/sync-knighted-css-types.mjs
// Do not edit manually.

declare global {
  interface KnightedCssGeneratedSelectors {
    '../src/components/stable_showcase.scss?knighted-css&types': Readonly<{
      readonly card: 'knighted-card'
      readonly copy: 'knighted-copy'
      readonly cta: 'knighted-cta'
      readonly tag: 'knighted-tag'
      readonly title: 'knighted-title'
    }>
  }
}

export type KnightedCssModuleId = keyof KnightedCssGeneratedSelectors
export type KnightedCssSelectorFor<Module extends KnightedCssModuleId> =
  KnightedCssGeneratedSelectors[Module]

export {}
