// Generated by @knighted/css/generate-types
// Do not edit.

export const stableSelectors = {
  card: 'knighted-card',
  copy: 'knighted-copy',
  cta: 'knighted-cta',
  tag: 'knighted-tag',
  title: 'knighted-title',
} as const

export type KnightedCssStableSelectors = typeof stableSelectors
export type KnightedCssStableSelectorToken = keyof typeof stableSelectors

export default stableSelectors
